[build]
target = "./index.html"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i input.css -o style/output.css"]

[serve]
address = "0.0.0.0"
port = 1420
open = false
ws_protocol = "ws"
